### ISSUE TITLE
x_rotation and y_rotation target selector

### ISSUE THREAD

**Issue by kikelkik** [ZombieStriker/PsudoCommands#2]
Hey,
I am wondering why a psudo command is not being executed if I provide a x_rotation and/or y_rotation tag in my target selector.

Example: /psudo msg @p[y_rotation=0..180] Hello
This command is supposed to be executed if the player is looking e.g. in south direction. But nothing happens.
Maybe you have to implement it same way you did with the 'limit' tag?

**Comment by ZombieStriker** [comment]
I forgot those selectors existed. Those will be added in the next update.

**Comment by kikelkik** [comment]
Are you sure it's implemented correctly? 
Example in Commandblock: 
psudo heal @p[distance=1..5] => works fine
psudo heal @p[distance=1..5,x_rotation=-90..90] =>nothing happens. "Previous Output in Commandblock: [13:09:57] An unexpected error occurred trying to execute that command"

in line 514 and 519 you define set `float pitch = getValueAsFloat(arg);` but don't refer to it later. Furthermore, in `isWithinYaw()` shouldn't it be `float yaw = getValueAsFloat(arg);` ?
